enable-magisk-update = true
parallel-jobs = 1
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"

[YouTube]
enabled = false
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
arch = "arm64-v8a"
build-mode = "both"

[Music]
enabled = false
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm64-v8a"
build-mode = "both"

[Spotify]
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
arch = "arm64-v8a"
build-mode = "both"
version = "9.0.44.471"
patches-source = "revanced/revanced-patches"
cli-source = "j-hc/revanced-cli"
rv-brand = "ReVanced"
