enable-magisk-update = true
parallel-jobs = 1
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
arch = "arm64-v8a"
build-mode = "both"

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm64-v8a"
build-mode = "both"

[Tiktok]
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
arch = "arm64-v8a"
build-mode = "both"
patches-source = "revanced/revanced-patches"
cli-source = "j-hc/revanced-cli"
rv-brand = "ReVanced"

[Instagram]
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram/"
arch = "arm64-v8a"
build-mode = "both"
patches-source = "revanced/revanced-patches"
cli-source = "j-hc/revanced-cli"
rv-brand = "ReVanced"

[Spotify]
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
arch = "arm64-v8a"
build-mode = "both"
patches-source = "revanced/revanced-patches"
cli-source = "j-hc/revanced-cli"
rv-brand = "ReVanced"
